version: '3.8'

services:
  prometheusX:
    image: bitnami/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafanaX:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana/var/lib:/var/lib/grafana
      - ./grafana/etc/grafana.ini:/etc/grafana/grafana.ini
    environment:
      # - GF_SECURITY_ADMIN_USER=admin
      # - GF_SECURITY_ADMIN_PASSWORD=StrongPassword123!
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini  # Optionnel : force Grafana à utiliser ce fichier
    ports:
      - "3000:3000"
    depends_on:
      - prometheusX
    networks:
      - monitoring

  alertmanager:
    image: bitnami/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager:/config
      - alertmanager_data:/alertmanager
    command: --config.file=/config/alertmanager.yml --log.level=debug
    ports:
      - "9093:9093"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  alertmanager_data: